### ISSUE TITLE
怎么把事务放在service层呢

### ISSUE THREAD

**Issue by zhump** [shhhplus/mysql-promise#4]

**Comment by shhhplus** [comment]
嗨，事务是数据操作层的活儿，不应该放在service层。mysql-promise仅仅是用来操作数据库的。

发自我的 iPhone

在 2016年8月27日，11:13，zhump <notifications@github.com<mailto:notifications@github.com>> 写道：

―

**Comment by zhump** [comment]
感谢回复， 一般涉及到事务，可能业务逻辑复杂点，比如 改->删  ,当删失败，改的操作应该回滚，这种操作是不是更像业务。 dao如果把改删都写在一起了，那还需要业务层吗？
还是说我对node的分层理解不对呢，，求指点

**Comment by shhhplus** [comment]
首先我觉得这和语言没有关系。操作数据库就应该在数据层。
如果一个逻辑比较复杂，是不是考虑不要写成一个事务，可以试着拆分逻辑，把拆分出来的小逻辑用事务。

发自我的 iPhone

在 2016年8月27日，11:38，zhump <notifications@github.com<mailto:notifications@github.com>> 写道：

感谢回复， 一般涉及到事务，可能业务逻辑复杂点，比如 改->删 ,当删失败，改的操作应该回滚，这种操作是不是更像业务。 dao如果把改删都写在一起了，那还需要业务层吗？
还是说我对node的分层理解不对呢，，求指点

―
